# Change these first
owner: RealNattawattHongthong # Your GitHub organization or username, where this repository lives
repo: uptime-version2 # The name of this repository

sites:
  - name: Main webpage
    url: https://nattawatt.com
  - name: Linktree
    url: https://tree.nattawatt.com
  - name: ProJect list
    url: https://project.nattawatt.com
  - name: Christmas Countdown
    url: https://christmas.nattawatt.com
  - name: Newyear Countdown
    url: https://newyear.nattawatt.com
  - name: Discord Bot Web
    url: https://discord.nattawatt.com
  - name: Archive Webpage
    url: https://archive.nattawatt.com
  - name: Thaiquote
    url: https://thaiquote.nattawatt.com
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime-version2
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
